// Unity build script. Just compile this with cl.exe on Windows
// cl.exe /std:c11 /W3 /D_CRT_SECURE_NO_WARNINGS unity.c
#include "src/array.c"
#include "src/context.c"
#include "src/gen.c"
#include "src/lexer.c"
#include "src/lower.c"
#include "src/main.c"
#include "src/parser.c"
#include "src/path.c"
#include "src/report.c"
#include "src/strbuf.c"
#include "src/string.c"
#include "src/threadpool.c"
#include "src/tree.c"
#include "src/utility.c"