// Unity build script. Just compile this with cl.exe on Windows
#include "src/array.c"
#include "src/context.c"
#include "src/lexer.c"
#include "src/main.c"
#include "src/parser.c"
#include "src/path.c"
#include "src/report.c"
#include "src/strbuf.c"
#include "src/string.c"
#include "src/thread.c"
#include "src/threadpool.c"
#include "src/tree.c"
#include "src/utility.c"