// Used to generate instructions.h
#include <stdio.h>
#include <ctype.h>
#include <string.h>

#define countof(x) (sizeof(x)/sizeof(*(x)))

static int imax(int x, int y) {
	return x > y ? x : y;
}

typedef struct InstructionInfo InstructionInfo;

struct InstructionInfo {
	const char *name;
	const char *c_op;
};

// signless int instructions
static const InstructionInfo INT[] = {
	{ "add", "+" },
	{ "sub", "-" },
	{ "mul", "*" },
	{ "quo", "/" },
	{ "rem", "%" },
};

// float instructions
static const InstructionInfo FLT[] = {
	{ "add", "+" },
	{ "sub", "-" },
	{ "mul", "*" },
	{ "div", "/" },
};

// comparison instructions (generated for signless int and float)
static const InstructionInfo CMP[] = {
	{ "eq", "==" },
	{ "ne", "!=" },
};

// relational instructions (sign matters here!)
static const InstructionInfo REL[] = {
	{ "lt",  "<"  },
	{ "lte", "<=" },
	{ "gt",  ">"  },
	{ "gte", ">=" },
};

// bitwise instructions
static const InstructionInfo BIT[] = {
	{ "and", "&"  },
	{ "or",  "|"  },
	{ "xor", "^"  },
	{ "shl", "<<" },
	{ "shr", ">>" },
};

static int len(const char *name, int ts, int bits) {
	return snprintf(0, 0, "%s%c%d", name, ts, bits);
}

static void gen(const char *kind, int ts, int bits, InstructionInfo info) {
	printf("%s(", kind);
	for (const char *ch = info.name; *ch; ch++)
		putchar(toupper(*ch));
	const int len = strlen(info.name);
	const int pad0 = 8 - (len + snprintf(0, 0, "%+d", bits));
	const int pad1 = 4 - len;
	const int pad2 = 4 - strlen(info.c_op);
	printf("%c%d,%*c\"%s\",%*c\"%s\",%*c%d)\n",
		toupper(ts),
		bits,
		pad0, ' ',
		info.name,
		pad1, ' ',
		info.c_op,
		pad2 - strlen(info.c_op), ' ',
		bits);
}

static void genint(void) {
	for (int log2 = 3; log2 < 8; log2++)
		for (size_t i = 0; i < countof(INT); i++)
				gen("INT", 'i', 1 << log2, INT[i]);
	putchar('\n');
}

static void genflt(void) {
	for (int log2 = 4; log2 < 7; log2++)
		for (size_t i = 0; i < countof(FLT); i++)
			gen("FLT", 'f', 1 << log2, FLT[i]);
	putchar('\n');
}

static void gencmp(void) {
	for (int log2 = 3; log2 < 8; log2++)
		for (int i = 0; i < countof(CMP); i++)
			gen("CMP", 'i', 1 << log2, CMP[i]);
	for (int log2 = 4; log2 < 7; log2++)
		for (size_t i = 0; i < countof(CMP); i++)
			gen("CMP", 'f', 1 << log2, CMP[i]);
	putchar('\n');
}

static void genrel(void) {
	for (int log2 = 3; log2 < 8; log2++)
		for (int s = 0; s < 2; s++)
			for (size_t i = 0; i < countof(REL); i++)
				gen("REL", "iu"[s], 1 << log2, REL[i]);
	for (int log2 = 4; log2 < 7; log2++)
		for (size_t i = 0; i < countof(REL); i++)
			gen("REL", 'f', 1 << log2, REL[i]);
	putchar('\n');
}

static void genbit(void) {
	for (int log2 = 3; log2 < 8; log2++)
		for (size_t i = 0; i < countof(BIT); i++)
			gen("BIT", 'i', 1 << log2, BIT[i]);
	putchar('\n');
}

void define(const InstructionInfo *infos, size_t size, const char *name) {
	printf("#ifndef %s\n", name);
	printf("#define %s(...)\n", name);
	printf("#endif\n\n");
}

#define DEFINE(name) \
	define(name, countof(name), #name)

#define UNDEF(name) \
	printf("#undef %s\n", #name)

int main(int argc, char **argv) {
	printf("// Generated by %s\n\n", argv[0]);
	DEFINE(INT);
	DEFINE(FLT);
	DEFINE(CMP);
	DEFINE(REL);
	DEFINE(BIT);
	genint(); 
	genflt();
	gencmp();
	genrel();
	genbit();
	UNDEF(BIT);
	UNDEF(REL);
	UNDEF(CMP);
	UNDEF(FLT);
	UNDEF(INT);
	return 0;
}