// Used to generate instructions.h
#include <stdio.h>
#include <ctype.h>
#define countof(x) (sizeof(x)/sizeof(*(x)))
static const char *upper(const char *string) {
  static char buffer[1024];
  char *p = buffer;
  for (const char *ch = string; *ch; *p++ = toupper(*ch++)) ;
  *p = '\0';
  return buffer;
}
int main(int argc, char **argv) {
  const int INT_SIZES[] = { 8, 16, 32, 64, 128 };
  static const char *INT_INSTR[] = {
    "add", "sub", "mul", "quo", "rem", "neg", "shl", "shr", "and", "or", "xor", "eq", "neq", "lt", "gt", "lteq", "gteq",
    "atom_wr", "atom_rd", "atom_xchg", "atom_cas", "atom_add", "atom_sub", "atom_and", "atom_or", "atom_xor",
  };
  const int FLT_SIZES[] = { 16, 32, 64 };
  static const char *FLT_INSTR[] = {
    "addf", "subf", "mulf", "divf", "eqf", "neqf", "ltf", "gtf", "lteqf", "gteqf",
  };
  size_t max = 0;
  for (size_t i = 0; i < countof(INT_INSTR); i++)
    for (size_t j = 0; j < countof(INT_SIZES); j++)
      for (size_t k = 0; k < 2; k++) {
        const size_t len = snprintf(0, 0, "%s%c%d", INT_INSTR[i], "iu"[k], INT_SIZES[j]);
        if (len > max) max = len;
      }
  for (size_t i = 0; i < countof(FLT_INSTR); i++)
    for (size_t j = 0; j < countof(FLT_SIZES); j++) {
      const size_t len = snprintf(0, 0, "%s%d", FLT_INSTR[i], FLT_SIZES[j]);
      if (len > max) max = len;
    }
  max++;
  printf("// Automatically generated by %s\n", argv[0]);
  printf("#ifndef INSTRUCTION\n");
  printf("#define INSTRUCTION(...)\n");
  printf("#endif\n\n");
  for (size_t i = 0; i < countof(INT_INSTR); i++)
    for (size_t j = 0; j < countof(INT_SIZES); j++)
      for (size_t k = 0; k < 2; k++) {
        printf("INSTRUCTION(");
        long space = max - printf("%s%c%d", upper(INT_INSTR[i]), "IU"[k], INT_SIZES[j]);
        printf(",%*c\"%s%c%d\")\n", (int)space, ' ', INT_INSTR[i], "iu"[k], INT_SIZES[j]);
      }
  for (size_t i = 0; i < countof(FLT_INSTR); i++)
    for (size_t j = 0; j < countof(FLT_SIZES); j++) {
      printf("INSTRUCTION(");
      long space = max - printf("%s%d", upper(FLT_INSTR[i]), FLT_SIZES[j]);
      printf(",%*c\"%s%d\")\n", (int)space, ' ',  FLT_INSTR[i], FLT_SIZES[j]);
    }
  printf("INSTRUCTION(UNDEF,%*c\"undef\")\n", (int)max - (sizeof("UNDEF") - 1), ' ');
  printf("\n");
  printf("#undef INSTRUCTION\n");
  return 0;
}