#ifndef INSTRUCTION
#define INSTRUCTION(...)
#endif

INSTRUCTION(NEGI32, "negi32")
INSTRUCTION(MULI32, "muli32")
INSTRUCTION(ADDI32, "addi32")
INSTRUCTION(SUBI32, "subi32")
INSTRUCTION(UNDEF,  "undef")

#undef INSTRUCTION